# analysis_options.yaml
# Place this file at the project root (beside pubspec.yaml)

# Base Flutter lint set
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - ios/**
    - android/**
    - linux/**
    - macos/**
    - windows/**
    - web/**
    - test/**.mocks.dart
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/generated/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Style
    prefer_single_quotes: true
    always_use_package_imports: true
    sort_pub_dependencies: false

    # Common Flutter ergonomics
    avoid_print: false          # we allow print/debugPrint during dev
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_late: true
    unnecessary_nullable_for_final_variable_declarations: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
